# Generated by Django 3.2.5 on 2021-07-28 12:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_member', models.BooleanField(default=False)),
                ('is_worker', models.BooleanField(default=False)),
                ('is_pastor', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('occupation', models.CharField(blank=True, max_length=25, null=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(help_text='E.g. +234 803 123 4567', max_length=128, null=True, region=None, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
