# Generated by Django 3.2.5 on 2021-07-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='announcements',
        ),
        migrations.AddField(
            model_name='service',
            name='announcement',
            field=models.TextField(default='Bible Study', max_length=255),
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
