# Generated by Django 3.2.5 on 2021-07-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_donation_tithe'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tithe',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
