# Generated by Django 3.2.5 on 2021-07-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20210729_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(default='temi@temitopesolesi.com.ng', max_length=255, verbose_name='email address'),
        ),
    ]
