# Generated by Django 3.2.5 on 2021-09-21 12:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20210920_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='worship',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Sunday ThanksGiving Service', 'Sunday ThanksGiving Service'), ('Sunday Service', 'Sunday Service'), ('Sunday Special Service', 'Sunday Special Service'), ('Tuesday Bible Study', 'Tuesday Bible Study'), ('Thursday Revival Service', 'Thursday Revival Service'), ('Special Programme', 'Special Programme')], max_length=255),
        ),
    ]
