# Generated by Django 3.2.5 on 2021-09-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20210921_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='worship',
        ),
    ]
